name: Initialize Dependencies
description: Install Python Poetry project dependencies


inputs:
  python-version:
    description: Python version to install
    required: false
    default: "3.10"
  no-dev:
    description: Whether to exclude tool.poetry.dev-dependencies in pyproject.toml
    required: false
    default: "false"
  poetry-install-cmd:
    description: Command to install all project dependencies
    required: false
    default: "poetry install"
  poetry-install-cmd-no-dev:
    description: Command to install project dependencies without dev-dependencies
    required: false
    default: "poetry install --no-dev"
  postargs:
    description: Append arguments to the install command
    required: false
    default: ""
  cache-buster:
    description: Append string to cache key
    required: false
    default: ""


runs:
  using: composite
  steps:

    - name: Install Python
      uses: actions/setup-python@v3
      with: {python-version: "${{ inputs.python-version }}"}

    - name: Install Poetry
      uses: abatilo/actions-poetry@v2.1.4

    - name: Configure Poetry
      shell: bash
      run: poetry config virtualenvs.in-project true

    - name: Cache venv
      id: cache
      uses: actions/cache@v2
      with:
        key: "init-deps-py-${{ runner.os }}-venv-${{ hashFiles('poetry.lock') }}-${{ join(inputs.*, '@') }}"
        path: .venv

    - name: Validate venv
      id: validate
      if: "steps.cache.outputs.cache-hit == 'true'"
      shell: bash
      run: |
        poetry env info --ansi
        temp_file="$(mktemp)"
        poetry env info --no-ansi > "$temp_file"
        if grep -qE "^Valid: +True" "$temp_file"; then
          echo "::set-output name=is-valid::true"
        else
          echo "::set-output name=is-valid::false"
        fi
        rm "$temp_file"

    # TODO: Evict cache on invalid venv: https://github.com/actions/cache/issues/2

    - name: Install dependencies
      id: install
      if: "steps.validate.outputs.is-valid != 'true'"
      shell: bash
      env: {INSTALL_CMD: "${{ inputs.no-dev == 'true' && inputs.poetry-install-cmd-no-dev || inputs.poetry-install-cmd }}"}
      run: |
        ${{ env.INSTALL_CMD }}${{ inputs.postargs }}
        echo "::set-output name=cmd::${{ env.INSTALL_CMD }}${{ inputs.postargs }}"

    - name: Validate venv
      id: validate2
      if: "steps.validate.outputs.is-valid != 'true'"
      shell: bash
      run: |
        poetry env info --ansi
        temp_file="$(mktemp)"
        poetry env info --no-ansi > "$temp_file"
        if ! grep -qE "^Valid: +True" "$temp_file"; then
          echo "::set-output name=is-valid::false"
          echo "Virtualenv is invalid" >&2
          exit 1
        fi
        echo "::set-output name=is-valid::true"
        rm "$temp_file"


outputs:
  python-version:
    description: Same as input
    value: ${{ inputs.python-version }}
  no-dev:
    description: Same as input
    value: ${{ inputs.no-dev }}
  poetry-install-cmd:
    description: Same as input
    value: ${{ inputs.poetry-install-cmd }}
  poetry-install-cmd-no-dev:
    description: Same as input
    value: ${{ inputs.poetry-install-cmd-no-dev }}
  postargs:
    description: Same as input
    value: ${{ inputs.postargs }}
  cache-buster:
    description: Same as input
    value: ${{ inputs.cache-buster }}
  cache-hit:
    description: If an exact match was found for the generated cache key
    value: ${{ steps.cache.outputs.cache-hit }}
  cache-was-valid:
    description: If the restored cache was valid
    value: ${{ steps.validate.outputs.is-valid }}
  cache-end-result-valid:
    description: If the restored cache was valid at the end of this action's run
    value: ${{ steps.validate2.outputs.is-valid }}
  install-cmd-out:
    description: Install command actually used by the action
    value: ${{ steps.install.outputs.cmd }}
