name: Initialize Dependencies
description: Install project dependencies


inputs:
  python-version:
    description: Python version to install
    required: false
    default: "3.10"
  no-dev-deps:
    description: Whether to exclude pyproject.toml tool.poetry.dev-dependencies
    required: false
    default: "true"
  cache-buster:
    description: Append string to cache key
    required: false
    default: ""
  install-cmd:
    description: Command to install all project dependencies
    required: false
    default: "poetry install"
  install-cmd-no-dev:
    description: Command to install project dependencies without dev-dependencies
    required: false
    default: "poetry install --no-dev"


runs:
  using: composite
  steps:

    - name: Install Python
      uses: actions/setup-python@v2
      with: {python-version: "${{ inputs.python-version }}"}

    - name: Install Poetry
      uses: abatilo/actions-poetry@v2.1.4

    - name: Configure Poetry
      shell: bash
      run: poetry config virtualenvs.in-project true

    - name: Cache venv
      id: cache
      uses: actions/cache@v2
      with:
        key: "${{ runner.os }}-venv-${{ hashFiles('poetry.lock') }}-${{ inputs.no-dev-deps }}-${{ inputs.cache-buster }}"
        path: .venv

    - name: Validate venv
      id: validate
      if: "steps.cache.outputs.cache-hit == 'true'"
      shell: bash
      run: |
        poetry env info --ansi
        if poetry env info --no-ansi |grep -qE "^Valid: +True"; then
          echo "::set-output name=is-valid::true"
        fi

    # TODO: Evict cache on invalid venv: https://github.com/actions/cache/issues/2

    - name: Install dependencies
      if: "steps.validate.outputs.is-valid != 'true'"
      shell: bash
      run: "${{ inputs.no-dev-deps == 'true' && inputs.install-cmd-no-dev || inputs.install-cmd }}"

    - name: Validate venv
      shell: bash
      run: |
        poetry env info --ansi
        poetry env info --no-ansi |grep -qE "^Valid: +True"


outputs:
  python-version:
    description: Same as input
    value: ${{ inputs.python-version }}
  no-dev-deps:
    description: Same as input
    value: ${{ inputs.no-dev-deps }}
  cache-buster:
    description: Same as input
    value: ${{ inputs.cache-buster }}
  install-cmd:
    description: Same as input
    value: ${{ inputs.install-cmd }}
  install-cmd-no-dev:
    description: Same as input
    value: ${{ inputs.install-cmd-no-dev }}
