on: [pull_request, push]

env:
  CACHE_BUSTER: "${{ format('{0}|{1}|{2}|{3}', github.run_id, github.run_number, github.run_attempt, github.job) }}"

jobs:

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]  # TODO windows-latest
    runs-on: "${{matrix.os}}"
    steps:
      - {name: Check out repository code, uses: actions/checkout@v2}
      - name: Init
        id: init
        uses: ./
        with: {cache-buster: "${{ env.CACHE_BUSTER }}", postargs: " && rm -v .venv/bin/python"}
        continue-on-error: true
      - name: Verify
        env: {CONCLUSION: "${{ steps.init.outcome }}", END_RESULT_VALID: "${{ steps.init.outputs.cache-end-result-valid }}"}
        run: |
          set -ux
          test "CONCLUSION: $CONCLUSION" == "CONCLUSION: failure"
          test "END_RESULT_VALID: $END_RESULT_VALID" == "END_RESULT_VALID: false"
