name: Test PostArgs

on:
  pull_request:
  push:

jobs:

  test-default:
    runs-on: ubuntu-latest
    steps:
      - {name: Check out repository code, uses: actions/checkout@v2}
      - {name: Copy test files, run: "cp -v tests/test-postargs/* ."}
      - {name: Initialize dependencies, uses: ./}
      - name: Verify dependencies
        run: |
          set -x
          poetry run pip freeze
          poetry run pip freeze |cut -d" " -f1 |tee /tmp/installed.txt
          grep -iFx pygments /tmp/installed.txt  # Include
          ! grep -iFx flake8 /tmp/installed.txt  # Exclude
          ! grep -iFx beautifulsoup4 /tmp/installed.txt  # Exclude

  test-postargs:
    runs-on: ubuntu-latest
    steps:
      - {name: Check out repository code, uses: actions/checkout@v2}
      - {name: Copy test files, run: "cp -v tests/test-postargs/* ."}
      - {name: Initialize dependencies, uses: ./, with: {postargs: "-E bs4"}}
      - name: Verify dependencies
        run: |
          set -x
          poetry run pip freeze
          poetry run pip freeze |cut -d" " -f1 |tee /tmp/installed.txt
          grep -iFx pygments /tmp/installed.txt  # Include
          ! grep -iFx flake8 /tmp/installed.txt  # Exclude
          grep -iFx beautifulsoup4 /tmp/installed.txt  # Include

  test-postargs-dev-deps:
    runs-on: ubuntu-latest
    steps:
      - {name: Check out repository code, uses: actions/checkout@v2}
      - {name: Copy test files, run: "cp -v tests/test-postargs/* ."}
      - {name: Initialize dependencies, uses: ./, with: {postargs: "-E bs4", no-dev-deps: "false"}}
      - name: Verify dependencies
        run: |
          set -x
          poetry run pip freeze
          poetry run pip freeze |cut -d" " -f1 |tee /tmp/installed.txt
          grep -iFx pygments /tmp/installed.txt  # Include
          grep -iFx flake8 /tmp/installed.txt  # Include
          grep -iFx beautifulsoup4 /tmp/installed.txt  # Include
